//LAB 4

public class StudentApp {
    public static void main(String[] args){
        Student s1 = new Student();
        s1.setName("Beatrix Kiddo");
        
        Student s2 = new Student();
        s2.setName("Dominic Toretto");
        
        System.out.println(s1.toString());
        System.out.println(s2.toString());
        
        //#4
        //to create a subclass you need to create an actual new class
        
        Undergraduate u1 = new Undergraduate(); //to create an object
        u1.setName("Barry Allen"); //has to be set according to superclass:
        u1.setMajor("Forensics");
        u1.setMinor("Athletics");
        u1.setCredits(25);
        u1.calculateFees();
        System.out.println(u1.toString());
        //from Student superclass state
        
        Undergraduate u2 = new Undergraduate();
        u2.setName("John Rambo");
        u2.setMajor("Conflict Analysis");
        u2.setMinor("International Affairs");
        u2.setCredits(20);
        u2.calculateFees();
        System.out.println(u2.toString());
        
        Undergraduate u3 = new Undergraduate();
        u3.setName("Jellen Ripley");
        u3.setMajor("Astrobiology");
        u3.setMinor("Conflict Analysis");
        u3.setCredits(15);
        u3.calculateFees();
        System.out.println(u3.toString());
        
        Postgraduate p1 = new Postgraduate("John McClain", "Prof Asp Pirin", "How to Die Hard");
        System.out.println(p1.toString());
        
        Postgraduate p2 = new Postgraduate("Brian Mills", "Dr No Kia", "Mobilr Usage Patterns in Hostage Situtations");
        p2.setStatus("Part Time");
        System.out.println(p2.toString());
        /* The id is autogenerated so ignore that but after creating
           an object*/
     }
}
